server:
  port: 9006

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/double?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jersey:
    application-path: ${spring.application.name}
    type: servlet
    servlet:
      load-on-startup: 1
    init: { jersey.config.beanValidation.enableOutputValidationErrorEntity.server: true }
